# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_horizontal = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_horizontal.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_horizontal.setObjectName("splitter_horizontal")
        self.splitter_vertical = QtWidgets.QSplitter(self.splitter_horizontal)
        self.splitter_vertical.setOrientation(QtCore.Qt.Vertical)
        self.splitter_vertical.setObjectName("splitter_vertical")
        self.ecs_elements = ECSElementsTreeWidget(self.splitter_vertical)
        self.ecs_elements.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ecs_elements.setIndentation(12)
        self.ecs_elements.setObjectName("ecs_elements")
        self.attributes = ECSAttributesTreeWidget(self.splitter_vertical)
        self.attributes.setObjectName("attributes")
        self.tabWidget = ECSTabView(self.splitter_horizontal)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout.addWidget(self.splitter_horizontal)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuECS_Taks_Operation = QtWidgets.QMenu(self.menubar)
        self.menuECS_Taks_Operation.setObjectName("menuECS_Taks_Operation")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionReload_Clusters = QtWidgets.QAction(MainWindow)
        self.actionReload_Clusters.setObjectName("actionReload_Clusters")
        self.actionReload_Config = QtWidgets.QAction(MainWindow)
        self.actionReload_Config.setObjectName("actionReload_Config")
        self.menuECS_Taks_Operation.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionReload_Config)
        self.menuFile.addAction(self.actionReload_Clusters)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuECS_Taks_Operation.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ecs_elements.headerItem().setText(0, _translate("MainWindow", "ECS Elements"))
        self.attributes.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.attributes.headerItem().setText(1, _translate("MainWindow", "Value"))
        self.menuECS_Taks_Operation.setTitle(_translate("MainWindow", "Help"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionReload_Clusters.setText(_translate("MainWindow", "Reload Clusters"))
        self.actionReload_Clusters.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionReload_Config.setText(_translate("MainWindow", "Reload Config"))
from ecs_tasks_ops_qt5.qt5_ecs import ECSAttributesTreeWidget, ECSElementsTreeWidget, ECSTabView
